# Generated by Django 2.2.13 on 2020-06-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_autor_name', models.CharField(max_length=40)),
                ('article_publishing_date', models.DateField(auto_now_add=True)),
                ('aritcle_modifield_date', models.DateField(auto_now_add=True)),
                ('article_title', models.CharField(max_length=20)),
                ('article_text', models.CharField(max_length=1024)),
                ('article_autor_ip', models.CharField(max_length=15)),
            ],
        ),
    ]
