# Generated by Django 2.2.13 on 2020-06-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('artigo_id', models.AutoField(primary_key=True, serialize=False)),
                ('artigo_autor_nome', models.CharField(max_length=40)),
                ('artigo_data_criacao', models.DateField(auto_now_add=True)),
                ('aritcle_data_modificacao', models.DateField(auto_now_add=True)),
                ('artigo_titulo', models.CharField(max_length=20)),
                ('artigo_texto', models.CharField(max_length=1024)),
                ('artigo_autor_ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
