# Generated by Django 2.2.13 on 2020-06-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200617_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='artigo_texto',
            field=models.TextField(max_length=1024),
        ),
    ]
