# Generated by Django 2.2.13 on 2020-06-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200617_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='artigo_resumo',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
