# Generated by Django 2.2.13 on 2020-06-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_artigo_artigo_resumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='artigo_keywords',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
